CREATE DATABASE IF NOT EXISTS MLFINANCES;
USE MLFINANCES;

CREATE TABLE IF NOT EXISTS USER(
	ID_USER INT AUTO_INCREMENT PRIMARY KEY,
    NIF INT(8),
    NAME VARCHAR(10),
    SURNAME VARCHAR(25),
    AGE INT,
    HASH VARCHAR(120),
    BAN BOOLEAN,
    ADMIN BOOLEAN,
    PROFILEPHOTO VARCHAR(60)    
    );
    
    CREATE TABLE IF NOT EXISTS ACCOUNT(
    ID_ACCOUNT INT AUTO_INCREMENT PRIMARY KEY,
    BALANCE FLOAT
    );
    
    CREATE TABLE IF NOT EXISTS MOVEMENT(
    ID_MOVEMENT INT auto_increment PRIMARY KEY,
    ID_FROMACCOUNT INT,
    ID_TOACCOUNT INT,
    CONCEPT VARCHAR (60)
    );
    
    CREATE TABLE IF NOT EXISTS LOAN(
    ID_LOAN INT AUTO_INCREMENT PRIMARY KEY,
    EXPEDITIONDATE DATE,
    MONTHLYPAYMENT FLOAT,
    TERMS INT,
    TOTAL FLOAT,
    INTEREST FLOAT,
    DUEDATE DATE
    );
    
    CREATE TABLE IF NOT EXISTS USER_ACCOUNT(
    ID_USER INT,
    ID_ACCOUNT INT,
    FOREIGN KEY (ID_USER) REFERENCES USER(ID_USER),
    FOREIGN KEY (ID_ACCOUNT) REFERENCES ACCOUNT(ID_ACCOUNT)
    );
    
    CREATE TABLE IF NOT EXISTS ACCOUNT_MOVEMENT(
    ID_ACCOUNT INT,
    ID_MOVEMENT INT,
    FOREIGN KEY (ID_ACCOUNT) REFERENCES ACCOUNT(ID_ACCOUNT),
    FOREIGN KEY (ID_MOVEMENT) REFERENCES MOVEMENT(ID_MOVEMENT)
    );
    
    CREATE TABLE IF NOT EXISTS ACCOUNT_LOAN(
    ID_ACCOUNT INT,
    ID_LOAN INT,
    FOREIGN KEY (ID_ACCOUNT) REFERENCES ACCOUNT(ID_ACCOUNT),
    FOREIGN KEY (ID_LOAN) REFERENCES LOAN(ID_LOAN)
    );
    
   